stages:
  - test

variables:
  NODE_VERSION: "18"

cache:
  paths:
    - node_modules/

playwright-tests:
  stage: test
  image: node:18
  before_script:
    - npm ci
    - npx playwright install --with-deps
  script:
    - npx playwright test
  artifacts:
    when: always
    paths:
      - playwright-report/
      - test-results/
    expire_in: 1 week
    reports:
      junit: test-results/results.xml
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

playwright-chrome-tests:
  stage: test
  image: node:18
  before_script:
    - npm ci
    - npx playwright install --with-deps
  script:
    - npx playwright test --project=chromium
  artifacts:
    when: always
    paths:
      - playwright-report/
      - test-results/
    expire_in: 1 week
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure 