# CI/CD Configuration for Playwright Automation
# This file contains configuration settings for both GitHub Actions and Jenkins

# Test Suite Configuration
test_suites:
  simple:
    name: "Simple Tests"
    description: "Basic page validation and structure verification"
    file: "tests/simple.spec.js"
    timeout_minutes: 15
    browser: "chromium"
    parallel: true
    artifacts: ["test-results", "screenshots"]
    
  ci_friendly:
    name: "CI-Friendly Tests"
    description: "Network connectivity and external service validation"
    file: "tests/ci-friendly.spec.js"
    timeout_minutes: 20
    browser: "chromium"
    parallel: true
    artifacts: ["test-results", "screenshots"]
    
  smoke:
    name: "Smoke Tests"
    description: "AI model validation and automation verification"
    file: "tests/SmokeSuite/smokeTesting.spec.js"
    timeout_minutes: 120
    browser: "chromium"
    parallel: false
    artifacts: ["test-results", "videos", "screenshots", "error-context"]
    requires_auth: true
    
  tool_validation:
    name: "Tool Validation Tests"
    description: "AI tool functionality and file upload validation"
    file: "tests/ToolValidation/toolValidation.spec.js"
    timeout_minutes: 90
    browser: "chromium"
    parallel: false
    artifacts: ["test-results", "videos", "screenshots", "error-context"]
    requires_auth: true

# Environment Configuration
environments:
  staging:
    url: "https://staging.ai.future.works/"
    auto_deploy: true
    required_reviews: 1
    protection: "strict"
    
  production:
    url: "https://ai.future.works/"
    auto_deploy: false
    required_reviews: 2
    protection: "strict"
    code_owner_reviews: true

# Browser Configuration
browsers:
  chromium:
    name: "Chromium"
    default: true
    headless: true
    slow_mo: 1000
    
  firefox:
    name: "Firefox"
    default: false
    headless: true
    slow_mo: 1000
    
  webkit:
    name: "WebKit"
    default: false
    headless: true
    slow_mo: 1000

# Parallel Execution Configuration
parallel_config:
  max_workers: 4
  simple_tests: 2
  ci_friendly_tests: 2
  smoke_tests: 1
  tool_validation_tests: 1

# Artifact Configuration
artifacts:
  retention_days: 30
  production_retention_days: 90
  include_patterns:
    - "test-results/**/*"
    - "playwright-report/**/*"
    - "screenshots/**/*"
    - "videos/**/*"
    - "error-context/**/*"
  exclude_patterns:
    - "node_modules/**/*"
    - ".git/**/*"
    - "*.log"

# Notification Configuration
notifications:
  slack:
    enabled: false
    webhook_url: "${SLACK_WEBHOOK_URL}"
    channels:
      - "#qa-automation"
      - "#devops"
      
  email:
    enabled: true
    recipients:
      - "qa-team@company.com"
      - "devops@company.com"
    on_failure: true
    on_success: false
    
  teams:
    enabled: false
    webhook_url: "${TEAMS_WEBHOOK_URL}"

# Security Configuration
security:
  secrets_required:
    - "STAGE_ENV"
    - "QA_USERNAME"
    - "QA_PASSWORD"
    
  branch_protection:
    main:
      required_reviews: 2
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
      require_status_checks: true
      required_status_checks:
        - "lint-validate"
        - "simple-tests"
        - "ci-friendly-tests"
        - "smoke-tests"
        
    develop:
      required_reviews: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: false
      require_status_checks: true
      required_status_checks:
        - "lint-validate"
        - "simple-tests"
        - "ci-friendly-tests"

# Deployment Configuration
deployment:
  staging:
    trigger: "automatic"
    conditions:
      - "all_tests_pass"
      - "branch_is_develop"
    steps:
      - "validate_environment"
      - "run_smoke_tests"
      - "deploy_application"
      - "verify_deployment"
      
  production:
    trigger: "manual"
    conditions:
      - "all_tests_pass"
      - "manual_approval"
      - "deployment_notes_provided"
    steps:
      - "validate_environment"
      - "run_full_test_suite"
      - "backup_current_version"
      - "deploy_application"
      - "verify_deployment"
      - "notify_stakeholders"

# Monitoring Configuration
monitoring:
  health_checks:
    - "application_availability"
    - "database_connectivity"
    - "external_api_connectivity"
    
  metrics:
    - "test_execution_time"
    - "test_success_rate"
    - "test_failure_rate"
    - "deployment_frequency"
    
  alerts:
    test_failure_threshold: 10
    deployment_failure_threshold: 1
    response_time_threshold: 300

# Resource Configuration
resources:
  github_actions:
    runner: "ubuntu-latest"
    timeout_minutes: 360
    memory: "7GB"
    disk_space: "14GB"
    
  jenkins:
    agent: "any"
    timeout_minutes: 360
    memory: "8GB"
    disk_space: "16GB"

# Schedule Configuration
schedule:
  daily_tests:
    cron: "30 5 * * *"  # 5:30 AM UTC (11:00 AM IST)
    timezone: "UTC"
    test_suites: ["all"]
    
  weekly_tests:
    cron: "0 10 * * 1"  # 10:00 AM UTC every Monday
    timezone: "UTC"
    test_suites: ["smoke", "tool-validation"]
    
  monthly_tests:
    cron: "0 11 1 * *"  # 11:00 AM UTC on the 1st of every month
    timezone: "UTC"
    test_suites: ["all"]
    browsers: ["chromium", "firefox", "webkit"]
