name: production
url: https://ai.future.works
protection_rules:
  required_reviews:
    required_approving_review_count: 2
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
  required_status_checks:
    strict: true
    contexts: []
  restrictions:
    users: []
    teams: []
