name: staging
url: https://staging.ai.future.works
protection_rules:
  required_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: false
  required_status_checks:
    strict: true
    contexts: []
  restrictions:
    users: []
    teams: []
